project 'Demo/Demo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Demo
#  pod 'YsSwift', :path => "../"
#  pod 'YsSwift/Rabbit', :path => "../"
  pod 'YsSwift/Rabbit',    :path => "../"
  pod 'YsSwift/Peacock',   :path => "../"
end

#配置pod工程中swift版本
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
